{"name": "Логин с неправильными учетными данными", "status": "passed", "description": "Тест проверяет попытку логина с неправильными учетными данными. Ожидается ошибка 401.", "steps": [{"name": "Попытка логина с email=ghjstjvweb@example.com и password=lquwvduvfuec", "status": "passed", "start": 1723209222987, "stop": 1723209223220}], "parameters": [{"name": "email", "value": "'ghjstjvweb@example.com'"}, {"name": "password", "value": "'lquwvduvfuec'"}], "start": 1723209222987, "stop": 1723209223222, "uuid": "f792585e-a151-46ec-81c6-a9fad7f07380", "historyId": "164c0cf6f1d5aad296162e77136497c0", "testCaseId": "ad4bdf1dbd143f644ff8c13f63194130", "fullName": "tests.test_user_login.TestUserLogin#test_login_incorrect_credentials", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup_teardown')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_login"}, {"name": "subSuite", "value": "TestUserLogin"}, {"name": "host", "value": "AmosovLenovo"}, {"name": "thread", "value": "11348-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_login"}]}